[package]
name = "github-repo-clone"
version = "0.1.2"
edition = "2021"

[[bin]]
name = "grc"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.1.9"
skim = "*"
regex = "1.5"
serde = "*"
serde_json = "*"
serde_derive = "*"
git2 = "0.13.25"
reqwest = { version = "0.11", features = ["blocking"] }

[profile.release]
debug = true

